
CREATE TABLE IF NOT EXISTS empleados (
	id  	BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre 	VARCHAR(50) UNIQUE NOT NULL,
	dep 	VARCHAR(20) NOT NULL,
	email 	VARCHAR(60) UNIQUE NOT NULL,
	edad 	INT NOT NULL
);
